obj-$(CONFIG_IONO_PI_V3) += ionopi-v3.o

ionopi-v3-objs := module.o
ionopi-v3-objs += ../commons/misc/misc.o
ionopi-v3-objs += ../commons/gpio/gpio.o
ionopi-v3-objs += ../commons/wiegand/wiegand.o
ionopi-v3-objs += ../commons/atecc/atecc.o
ionopi-v3-objs += pcf2131/pcf2131.o
