# SPDX-License-Identifier: GPL-2.0
#
# Makefile for RP1 Camera Front End driver
#
rp1-cfe-objs := cfe.o csi2.o pisp_fe.o dphy.o
rp1-csi-test-objs := csi_test.o dphy.o
obj-$(CONFIG_VIDEO_RP1_CFE) += rp1-cfe.o rp1-csi-test.o
