subdir-ccflags-y += -I$(srctree)/arch/arm64/kvm/hyp/include/
subdir-ccflags-y += -DMODULE
hyp-obj-y := arm-smmu-v3.o io-pgtable-arm.o  ../../../io-pgtable-arm-common.o
include $(srctree)/arch/arm64/kvm/hyp/nvhe/Makefile.module
