obj-$(CONFIG_BCM2708_VCMEM)	+= vc_mem.o
obj-$(CONFIG_BCM_VCIO)		+= vcio.o
obj-$(CONFIG_BCM_VC_SM)         += vc_sm/

obj-$(CONFIG_BCM2835_DEVGPIOMEM)+= bcm2835-gpiomem.o
obj-$(CONFIG_BCM2835_SMI_DEV)	+= bcm2835_smi_dev.o
